[package]
name = "insecure_transaction"
version = "1.0.0"
authors = []

[addresses]
improper_access_control = "0x6f6a7cf03a0cb3b298da819f1e7821e76a80d9805ebb77e1c1ff4bd58bb55388"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
